name: Journey
favicon: null
layout_spectrum: 0.369619743200019
typography_spectrum: 0.33346624625846744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4860338044818491
  lightness: 0.0855127009563148
  saturation: 0.8835924551822245
  rhythmicContrast: 0.16381539101712406
purpose: []
