name: Journey
favicon: null
layout_spectrum: 0.369619743200019
typography_spectrum: 0.38356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b1b4b6'
    - '#ee3837'
    - '#303030'
  brandStrength: 0.4860338044818491
  lightness: 0.0855127009563148
  saturation: 0.8835924551822245
  rhythmicContrast: 0.16381539101712406
purpose: []
